### ISSUE TITLE
SmartTracker iOS doesn't compile with carthage

### ISSUE THREAD

**Issue by kenji21** [at-internet/atinternet-apple-sdk#52]
```
kenji@macboo:/tmp/atissue $ carthage update
*** Fetching atinternet-apple-sdk
*** Checking out atinternet-apple-sdk at "2.13.0"
*** xcodebuild output can be found in /var/folders/7v/dfg0p2vj1z58n65d99l2n1lh0000gp/T/carthage-xcodebuild.eo4rZJ.log
*** Building scheme "SmartTracker iOS" in ATAnalytics.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /private/tmp/toto/Carthage/Checkouts/atinternet-apple-sdk/ATAnalytics.xcworkspace -scheme SmartTracker\ iOS -configuration Release -derivedDataPath /Users/kenji/Library/Caches/org.carthage.CarthageKit/DerivedData/10.1_10B61/atinternet-apple-sdk/2.13.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/7v/dfg0p2vj1z58n65d99l2n1lh0000gp/T/atinternet-apple-sdk SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /tmp/toto/Carthage/Checkouts/atinternet-apple-sdk)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/7v/dfg0p2vj1z58n65d99l2n1lh0000gp/T/carthage-xcodebuild.eo4rZJ.log

kenji@macboo:/tmp/atissue $ cat Cartfile
github "at-internet/atinternet-apple-sdk" ~> 2.8
```

In the log file:

```
.../Carthage/Checkouts/atinternet-apple-sdk/ATInternetTracker/Sources/Tracker.swift:583:55: error: use of undeclared type 'ECommerce'
    @objc fileprivate(set) public lazy var ecommerce: ECommerce = ECommerce(tracker: self)
                                                      ^~~~~~~~~
.../Carthage/Checkouts/atinternet-apple-sdk/ATInternetTracker/Sources/Tracker.swift:632:56: error: use of undeclared type 'MvTestings'
    @objc fileprivate(set) public lazy var mvTestings: MvTestings = MvTestings(tracker: self)
```

and 111 warnings (assuming 1 percent of them will provoque an error... 1.1 errors...)

**Comment by kenji21** [comment]
works fine in 2.11.0

**Comment by nsagnett** [comment]
Sorry but SmartTracker was deprecated since 2.12.0 version, so the files added for this release are not joined to SmartTracker target

**Comment by kenji21** [comment]
So I have to stay on 2.11 ? Don't SmartTracker target might be removed from the Xcode project ?

Steps to reproduce the issue:

```
$ brew install carthage
$ mkdir /tmp/issue-52 && cd /tmp/issue-52
$ echo 'github "at-internet/atinternet-apple-sdk" ~> 2.8' > Cartfile
$ carthage update
```
